export const Currencies = [
    {code: 'CAD', name: 'Canadian Dollar'},
    {code: 'EUR', name: 'Euro'},
    {code: 'HKD', name: 'Hong Kong Dollar'},
    {code: 'ISK', name: 'Icelandic Króna'},
    {code: 'PHP', name: 'Philippine Peso'},
    {code: 'DKK', name: 'Danish Krone'},
    {code: 'HUF', name: 'Hungarian Forint'},
    {code: 'CZK', name: 'Czech Koruna'},
    {code: 'AUD', name: 'Australian Dollar'},
    {code: 'RON', name: 'Romanian Leu'},
    {code: 'SEK', name: 'Swedish Krona'},
    {code: 'IDR', name: 'Indonesian Rupiah'},
    {code: 'INR', name: 'Indian Rupee'},
    {code: 'BRL', name: 'Brazilian Real'},
    {code: 'RUB', name: 'Russian Ruble'},
    {code: 'HRK', name: 'Croatian Kuna'},
    {code: 'JPY', name: 'Japanese Yen'},
    {code: 'THB', name: 'Thai Baht'},
    {code: 'CHF', name: 'Swiss Franc'},
    {code: 'SGD', name: 'Singapore Dollar'},
    {code: 'PLN', name: 'Polish Złoty'},
    {code: 'BGN', name: 'Bulgarian Lev'},
    {code: 'TRY', name: 'Turkish Lira'},
    {code: 'CNY', name: 'Chinese Yuan'},
    {code: 'NOK', name: 'Norwegian Krone'},
    {code: 'NZD', name: 'NZ Dollar'},
    {code: 'ZAR', name: 'South African Rand'},
    {code: 'USD', name: 'US Dollar'},
    {code: 'MXN', name: 'Mexican Peso'},
    {code: 'ILS', name: 'Israeli New Shekel'},
    {code: 'GBP', name: 'Pound Sterling'},
    {code: 'KRW', name: 'South Korean Won'},
    {code: 'MYR', name: 'Malaysian Ringgit'}
];
